apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gatewayservice
  name: gatewayservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gatewayservice
    spec:
      containers:
      - image: llinda/docker-gateway
        name: docker-gateway
        resources: {}
status: {}
--- 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  ports:
  - name: 9090-9090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: demo
  type: ClusterIP
status:
  loadBalancer: {}
