spring:
  application:
    name: ${spring.application.name}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:  eureka:    enabled: true
  restclient:    enabled: true
     